CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

CREATE INDEX IDX_USERS_NAME ON USERS (NAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);

CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE INDEX IDX_ROLES_NAME ON ROLES (NAME);

CREATE TABLE USER_ROLES (
    USER_ID UUID NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_USER_ROLES_USER_ID ON USER_ROLES (USER_ID);
CREATE INDEX IDX_USER_ROLES_ROLE_ID ON USER_ROLES (ROLE_ID);
